FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y nginx
RUN rm /var/www/html/index.nginx-debian.html

COPY static/index.html /var/www/html/
COPY script.js /var/www/html/
COPY static/style.css /var/www/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

