name: bad workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore sem_1/test

    - name: Build
      run: dotnet build --no-restore sem_1/test

    - name: Run static analysis
      run: dotnet format sem_1/test/testapp/testapp.csproj analyzers

    - name: Publish
      run: dotnet publish sem_1/test/testapp/testapp.csproj -c Release -o output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Deploy application
      run: echo "deploy was successful"
