version: '3.9'
services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    mem_limit: 512m
    cpus: "2.0"
    command: sh -c "python3 manage.py migrate && uwsgi --ini uwsgi.ini"
    
  db:
    image: postgres:14.7-alpine
    env_file:
      - .env
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app -U worker"]
      interval: 10s
      timeout: 20s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      sh -c "
      docker-entrypoint.sh postgres &&
      cp pg_hba.conf /var/lib/postgresql/data/pg_hba.conf &&
      pg_ctl reload
      "
    mem_limit: 512m
    cpus: "1.0"
    restart: always

volumes:
  postgres_data:

